### ISSUE TITLE
Negative result

### ISSUE THREAD

**Issue by rgv151** [rbmz/stopwatch#1]
sometime I got negative result, very strange

please check this bench for example: https://gist.github.com/rgv151/460fdc627cf0476ab1e1

**Comment by rbmz** [comment]
I could not reproduce, but from the output it seems a 32-bit overflow issue. Could you please test if my commit fixed it for you?

**Comment by rgv151** [comment]
i dont face this problem again on Ubuntu 64bit, but I will test again on Mac OSX when I get back home. thanks

**Comment by rbmz** [comment]
Assuming fixed. Please reopen if this comes up again.
