### ISSUE TITLE
I made a fork and added features

### ISSUE THREAD

**Issue by define-private-public** [rbmz/stopwatch#3]
Hi,

I was using this module before for some bench marking, but I had some cases were I wanted to measure laps, so I added that functionality.  If you're interested in using the code I wrote, I can submit a PR, as you own the "stopwatch," name in nimble.  Everything is documented.  The only thing that I removed was the `bench` template, but I can put it back in there if you think it's a good idea.

Code is here: https://gitlab.com/define-private-public/stopwatch/blob/79f3a0d91b14ef2c3ad7ce5ad937f1aef2e4ba27/stopwatch.nim

I still need to update the README file.

**Comment by define-private-public** [comment]
README updated.

**Comment by define-private-public** [comment]
I tried to put my fork on nimble, but when doing so, it was mentioned I should swap out your URL with mine;  I did so:

https://github.com/nim-lang/packages/pull/437#issuecomment-266276220

**Comment by rbmz** [comment]
Nice new features! but I would appreciate it if you make it backwards compatible. As it is now it breaks my code and probably other people's code.

```
## Converts nanoseconds to seconds (represented as a float)
proc secs*(nsecs: int64): float =
  return nsecs.float / 1_000_000_000.0
```
I think this should be a float64, as it seemed to fix [this issue](https://github.com/rbmz/stopwatch/issues/1)

**Comment by rbmz** [comment]
newStopwatch should be called initStopwatch because Stopwatch is not a reference type

**Comment by define-private-public** [comment]
I chnaged `newStopwatch()` over to `stopwatch()`.

As for the backwards compatibility, I added some deprecation pragmas; they usually can catch what is out of date. The only thing that I can think that breaks is that you have to do `var sw = stopwatch()` instead of doing `var c:clock`.  And that's because of the nature of the `Stopwatch` object.  I also took out the `bench` template.  I could add it back in if you want.

As for the float64 issue, I haven't been able to produce it.  And the nim manual says that the `float` type should correspond to a 64 bit floating point.

**Comment by rbmz** [comment]
Yes, I think it's better to add the bench template back (perhaps deprecate it and find a better name?) because it's pretty annoying to refactor it to the new way.

One of my projects was not as easy to port (relied on start/stop/secs logic that changed), but it ended up being cleaner.

reported 2 issues:
https://github.com/define-private-public/stopwatch/issues/1
https://github.com/define-private-public/stopwatch/issues/2

**Comment by rbmz** [comment]
Would have made a PR at least for #1 but as that's a mirror I preferred not to.

**Comment by define-private-public** [comment]
what do you think would be a better name for `bench`?

Also, should it take an already existing `Stopwatch` object, or create a new one?

**Comment by rbmz** [comment]
I don't know of a better name.

I tested it and just adding back the version of bench that you removed seems to work well

Here it is (updated to latest nim and stopwatch):
```
template bench*(c: Stopwatch, body: untyped): untyped =
  c.start()
  body
  c.stop()
```

**Comment by define-private-public** [comment]
Okay, I'll put that in

**Comment by define-private-public** [comment]
Okay, bench is added in.  I had to also put a call to `c.stop()` at the top of the template because the bench that you posted assumes that a Stopwatch isn't already running.

**Comment by define-private-public** [comment]
Can you think of any good unit tests?  Right now I have that `tester.nim`.  It shows off all of the main features, but I don't think it's good enough.

**Comment by rbmz** [comment]
```
  var c, c0, c1, c2 = stopwatch()
  
  bench(c):
    bench(c0):
      sleep(100)
    bench(c1):
      sleep(50)
    bench(c2):
      for i in 0..<2:
        sleep(1)

  echo "bench 0): ", c0.secs
  echo "bench 1): ", c1.secs
  echo "bench 2): ", c2.secs
  echo "total: ", c.secs
```
add this one if you think it's worth it. another idea could be to add conservative assertions for time ranges.

**Comment by define-private-public** [comment]
I honestly not sure what or how to unit test this thing really.  We want time to be over a certain amount, but under another one as well.  The precision on different platforms is what bites us in the but.

Also, in an un-related note, could you pull this down and run the unit tests for me on Windows & Wine: https://github.com/define-private-public/stb_image-Nim  I tried to run it myself on the Microsoft product but I've been having issues with getting Nim to work there properly.  I'd be very appreciative if you could.

**Comment by rbmz** [comment]
Your wrapper passed the tests both in wine and windows.
Mind you, I don't have nim set up in windows. I'm cross-compiling from linux with this line (needs mingw):
```
nim c --cpu:i386 --os:windows --passC:-m32 --passL:-m32 --deadCodeElim:on --cc:gcc --gcc.exe="i686-w64-mingw32-gcc" --gcc.linkerexe="i686-w64-mingw32-gcc" -d:release file.nim
```

**Comment by define-private-public** [comment]
Alright, I'm going to close this issue for now, as there doesn't seem to be anything relevant anymore here.
